services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./ddl/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      POSTGRES_DB: "cars-db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "v1234567"
    networks:
      - default  
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - default
    env_file:
      - ./.env
networks:
  default:
